# config
spring:
    application:
      name: le-share
    data:
      mongodb:
        host: 127.0.0.1
        port: 27017
        authentication-database: le-share
        database: le-share
        username: admin
        password: admin
        #每个主机的连接数
        connections-per-host: 50
        #线程队列数，它以上面connectionsPerHost值相乘的结果就是线程队列最大值
        threads-allowed-to-block-for-connection-multiplier: 50
        connect-timeout: 5000
        socket-timeout: 3000
        max-wait-time: 1500
        #控制是否在一个连接时，系统会自动重试
        auto-connect-retry: true
        socket-keep-alive: true

    servlet:
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB
    http:
      encoding:
        charset: utf-8
        enabled: true
        force: true

server:
  port: 8086
  address: 0.0.0.0
  servlet:
    context-path: /
